### ISSUE TITLE
Error while training and testing

### ISSUE THREAD

**Issue by thisisashukla** [kayoyin/transformer-slt#3]
Hi, thanks for this open source repo. I am trying to execute the commands given in the README. I am receiving the following error. Any help would be appricated.

```
(py36torch) E:\transformer-slt>python  train.py -data data/dgs -save_model model -keep_checkpoint 1 -layers 2 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8  -encoder_type transformer -decoder_type transformer -position_encoding -max_generator_batches 2 -dropout 0.1 -early_stopping 3 -early_stopping_criteria accuracy ppl -batch_size 2048 -accum_count 3 -batch_type tokens -normalization tokens -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 3000 -learning_rate 0.5 -max_grad_norm 0 -param_init 0  -param_init_glorot -label_smoothing 0.1 -valid_steps 100 -save_checkpoint_steps 100 -world_size 1 -gpu_ranks 0
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    main()
  File "E:\transformer-slt\onmt\bin\train.py", line 204, in main
    train(opt)
  File "E:\transformer-slt\onmt\bin\train.py", line 35, in train
    vocab = torch.load(opt.data + '.vocab.pt')
  File "E:\Envs\py36torch\lib\site-packages\torch\serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\Envs\py36torch\lib\site-packages\torch\serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\Envs\py36torch\lib\site-packages\torch\serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/dgs.vocab.pt'
```

When i execute the testing command i am getting the following error:

```
(py36torch) E:\transformer-slt>python translate.py -model model [model2 model3 ...] -src data/phoenix2014T.test.gloss -output pred.txt -gpu 0 -replace_unk -beam_size 4
Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "E:\transformer-slt\onmt\bin\translate.py", line 48, in main
    translate(opt)
  File "E:\transformer-slt\onmt\bin\translate.py", line 18, in translate
    translator = build_translator(opt, report_score=True)
  File "E:\transformer-slt\onmt\translate\translator.py", line 28, in build_translator
    fields, model, model_opt = load_test_model(opt)
  File "E:\transformer-slt\onmt\decoders\ensemble.py", line 130, in load_test_model
    onmt.model_builder.load_test_model(opt, model_path=model_path)
  File "E:\transformer-slt\onmt\model_builder.py", line 96, in load_test_model
    map_location=lambda storage, loc: storage)
  File "E:\Envs\py36torch\lib\site-packages\torch\serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\Envs\py36torch\lib\site-packages\torch\serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\Envs\py36torch\lib\site-packages\torch\serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model'
```
Please suggest the solution

**Comment by thisisashukla** [comment]
I missed the pre-processing step.
